### ISSUE TITLE
Peer to Peer code review

### ISSUE THREAD

**Issue by NitBravoA92** [M-Anwar-Hussaini/Genius-Academy#6]
Great job so far @M-Anwar-Hussaini 👏
Your code is very clean, well structured, understandable, and follows good practices. 😎
However, there are some additional suggestions that you could take into account to improve your code:

- It would be good to pay special attention to using comments in your code. The use of comments in source code is not a bad practice, as long as they are not used excessively or for no real reason. Comments should be reserved to explain a section with complicated logic or have specific rules that need to be explained. Comments should be short, concise, and applicable, they should be limited to explaining why you are using a code block, and what is the purpose of that code block. Your code is very well structured and understandable, so some of your comments, especially those in your CSS code, can easily be omitted, for a much cleaner code. 🙌

**Comment by cancelei** [comment]
The code looks very clean and nice, I have some suggestions for the HTML file:

I suggest you use Alt Text to Images: For accessibility purposes, provide descriptive alt text for the <'img>' elements. Alt text helps visually impaired users understand the content of the images when they cannot be displayed.

I also suggest using Semantic HTML Elements: Instead of using generic <'div>' elements for sections, consider using semantic HTML elements like <'header>', <'main>', <'section>', and <'footer>'. This will improve the accessibility and structure of the code.

Happy coding!
